app:
  name: openaiserver
  version: v1.0
  isDev: true #是否本地调试
  logLevel: info
server:
  http:
    addr: 127.0.0.1:8003
    timeout: 60s
    jwtSecrect: asdf
data:
  baseServerAddr: dns:///127.0.0.1:9001
  baseServerRequestTimeout: 30s
  redis:
<<<<<<< Updated upstream
    addr: 192.168.202.73:31570
=======
    addr: 192.168.202.73:32185
>>>>>>> Stashed changes
    username:
    password: abcde
service:
  tokenExpirationSec: 86400
