---
kind: pipeline
type: kubernetes
name: linter
platform:
  os: linux
  arch: amd64
trigger:
  branch:
    - master
    - dev
  event:
    - push
steps:
  - name: 代码检查
    image: golangci/golangci-lint:v1.40.1
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    commands:
      - make lint

---
kind: pipeline
name: base-server
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  # - name: 代码检查
  #   image: golangci/golangci-lint:v1.40.1
  #   environment:
  #     GO111MODULE: on
  #     GOPROXY: https://goproxy.cn,direct
  #   commands:
  #     - make base-server_lint

  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make base-server_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make base-server_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: admin-server
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  # - name: 代码检查
  #   image: golangci/golangci-lint:v1.40.1
  #   environment:
  #     GO111MODULE: on
  #     GOPROXY: https://goproxy.cn,direct
  #   commands:
  #     - make admin-server_lint

  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make admin-server_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make admin-server_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: openai-server
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  # - name: 代码检查
  #   image: golangci/golangci-lint:v1.40.1
  #   environment:
  #     GO111MODULE: on
  #     GOPROXY: https://goproxy.cn,direct
  #   commands:
  #     - make openai-server_lint

  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make openai-server_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make openai-server_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: taskset/pipeline
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  # - name: 代码检查
  #   image: golangci/golangci-lint:v1.40.1
  #   environment:
  #     GO111MODULE: on
  #     GOPROXY: https://goproxy.cn,direct
  #   commands:
  #     - make taskset_lint

  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make pipeline_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make pipeline_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: taskset/vc-controller
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  # - name: 代码检查
  #   image: golangci/golangci-lint:v1.40.1
  #   environment:
  #     GO111MODULE: on
  #     GOPROXY: https://goproxy.cn,direct
  #   commands:
  #     - make taskset_lint

  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make vc-controller_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make vc-controller_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: taskset/scheduler
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  # - name: 代码检查
  #   image: golangci/golangci-lint:v1.40.1
  #   environment:
  #     GO111MODULE: on
  #     GOPROXY: https://goproxy.cn,direct
  #   commands:
  #     - make taskset_lint

  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make scheduler_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make scheduler_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: charts
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: dockeretc
    host:
      path: /etc/docker
steps:
  - name: Chart构建
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/helm:3.5.4-make
    volumes:
      - name: dockeretc
        path: /etc/docker
    environment:
      HARBOR_HUB_HOST:
        from_secret: harbor_hub_host
      HARBOR_HUB_USERNAME:
        from_secret: harbor_hub_userame
      HARBOR_HUB_PASSWD:
        from_secret: harbor_hub_passwd
      HARBOR_HUB_CA_FILE:
        from_secret: harbor_hub_ca_file
      HARBOR_HUB_CERT_FILE:
        from_secret: harbor_hub_cert_file
      CHARTS_GIT_CLONE:
        from_secret: charts_git_clone
      CHARTS_GIT_RAW:
        from_secret: charts_git_raw
      CHARTS_GIT_USER_NAME:
        from_secret: charts_git_user_name
      CHARTS_GIT_USER_EMAIL:
        from_secret: charts_git_user_email
      HARBOR_HUB_PROJECT:
        from_secret: harbor_hub_project
    commands:
      - make charts drone_repo=${DRONE_REPO} tag=${DRONE_TAG} harbor_hub_project=$HARBOR_HUB_PROJECT harbor_hub_host=$HARBOR_HUB_HOST harbor_hub_userame=$HARBOR_HUB_USERNAME harbor_hub_passwd=$HARBOR_HUB_PASSWD harbor_hub_ca_file=$HARBOR_HUB_CA_FILE HARBOR_HUB_CERT_FILE=$HARBOR_HUB_CERT_FILE charts_git_clone=$CHARTS_GIT_CLONE charts_git_raw=$CHARTS_GIT_RAW charts_git_user_name=$CHARTS_GIT_USER_NAME charts_git_user_email=$CHARTS_GIT_USER_EMAIL

---
kind: pipeline
name: admin-portal
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make admin-portal_image tag=${DRONE_TAG}
  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make admin-portal_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: openai-portal
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  - name: 构建镜像
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    commands:
      - make openai-portal_image tag=${DRONE_TAG}
  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make openai-portal_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD
