apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-storage
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"


#---

#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: nfs-mysql
#provisioner: nfs-storage
#reclaimPolicy: Retain
#volumeBindingMode: WaitForFirstConsumer
#parameters:
#  archiveOnDelete: "false"