apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS octopus DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
    CREATE DATABASE IF NOT EXISTS core DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-initdb-config
data:
  custom-init-scripts.sh: |
    influx -execute "CREATE DATABASE octopus" -username octopus -password octopus
    influx -execute "CREATE RETENTION POLICY \"default\" ON octopus DURATION 0s REPLICATION 1 DEFAULT"  -username {{ .Values.influxdb.auth.user.username }} -password {{ .Values.influxdb.auth.user.password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-exist-config
data:
  influxdb.conf: |
    [meta]
      dir = "/bitnami/influxdb/meta"
      logging-enabled = true
    [data]
      dir = "/bitnami/influxdb/data"
      wal-dir = "/bitnami/influxdb/wal"
      query-log-enabled = true
      cache-max-memory-size = 0
      max-series-per-database = 0
      max-values-per-tag = 0
      series-id-set-cache-size = 100
    [logging]
      format = "logfmt"
      level = "debug"
      suppress-logo = true
