apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ambassador.fullname" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ambassador.fullname" . }}
  labels:
{{ include "ambassador.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ template "ambassador.port" . }}
      targetPort: {{ template "ambassador.targetPort" . }}
  selector:
  {{ include "ambassador.select-labels" . | indent 8 }}


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ambassador.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "ambassador.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "ambassador.fullname" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ambassador.fullname" . }}
spec:
  selector:
    matchLabels:
  {{ include "ambassador.select-labels" . | indent 8 }}
  replicas: 1
  template:
    metadata:
      labels:
    {{ include "ambassador.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "ambassador.fullname" . }}
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: {{ .Chart.Name }}
          image: "datawire/ambassador:1.14.2"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args: []
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - name: {{ template "ambassador.name" . }}
              containerPort: {{ template "ambassador.port" . }}
          resources:
      {{ toYaml .Values.resources | indent 10 }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}