apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sftpgo.fullname" . }}
  labels:
  {{ include "sftpgo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.sftpgo.replicaCount }}
  selector:
    matchLabels:
  {{ include "sftpgo.select-labels" . | indent 8 }}
  template:
    metadata:
      labels:
    {{ include "sftpgo.labels" . | indent 8 }}
    spec:
      nodeSelector:
      {{- with .Values.global.nodeSelector }}
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.sftpgo.nodeSelector }}
      {{ toYaml . | indent 2 }}
      {{- end }}
      containers:
        - image: drakkan/sftpgo:{{ .Values.sftpgo.image.tag }}
          name: sftpgo
          resources:
  {{ toYaml .Values.grafana.resources | indent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sftpgo.webServiceName" . }}
  labels:
  {{ include "sftpgo.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sftpgo.service.webPort }}
      nodePort: {{ .Values.sftpgo.service.webNodePort }}
  selector:
  {{ include "sftpgo.select-labels" . | indent 6 }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "sftpgo.sftpServiceName" . }}
  labels:
  {{ include "sftpgo.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.sftpgo.service.sftpPort }}
      nodePort: {{ .Values.sftpgo.service.sftpNodePort }}
  selector:
  {{ include "sftpgo.select-labels" . | indent 6 }}