app:
  name: baseserver
  version: v1.0
  isDev: true #是否本地调试
  logLevel: info
server:
  http:
    addr: 0.0.0.0:8001
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 60s
data:
  database:
    driver: mysql
    source: root:root@tcp(192.168.202.73:30336)/octopus?charset=utf8&parseTime=True&loc=Local
  kubernetes:
    masterUrl: https://192.168.202.73:6443/
    configPath: ./kubeconfig
  pipeline:
    baseUrl: http://127.0.0.1:8080
    token: KLtmMug9BDvvRjlg
  minio:
    base:
      endPoint: 192.168.202.73:31311
      accessKeyID: minioadmin
      secretAccessKey: minioadmin
      useSSL: false
      mountPath: /data
      pvcName: octopus-minio-pvc
      proxyPath: /oss
    business:
      downloadExpiry: 86400
      uploadExpiry: 86400
  harbor:
    host: 192.168.202.74:5000
    username: openi
    password: OpenI2018
    apiVersion: v1.0
    useSSL: false
  redis:
    addr: 192.168.202.73:30459
    username:
    password: abcde
  jointCloud:
    baseUrl: http://192.168.207.141:8709
    username: test
    password: 6c7c824d3b7342a9dcc9b931f5662b18
service:
  baseServerAddr: http://127.0.0.1:8001
  dockerDatasetPath: /dataset
  dockerCodePath: /code
  dockerModelPath: /model
  resourceLabelKey: octopus.pcl.ac.cn/type
  billingPeriodSec: 60
  develop:
    jpyBaseUrlEnv: OCTOPUS_JPY_BASE_URL
    autoStopIntervalSec: 7200
  resource:
    customizedResourceBindingNodeLabelKeyFormat: openi.octopus.resource.%s
    customizedResourceBindingNodeLabelValue: bound
    defaultPoolName: common-pool
    poolInfoStoreKey: ResourcePoolInfo
    poolBindingNodeLabelKeyFormat: openi.octopus.resourcepool.%s
    poolBindingNodeLabelValue: bound
    poolSelectLabelKey: platform
    poolSelectLabelValue: openi.octopus
    discoveryLeaderLeaseLockName: resourcediscovery
    discoveryDuration: 15s
    ignoreSystemResources: hugepages-1Gi,pods,hugepages-2Mi,ephemeral-storage
  platform:
    # 数组内字段为
    # key：键值，必填，保存配置时传入
    # title：标题，必填
    # type：类型，必填，input、radio、checkbox
    # desc：描述，选填
    # options：选项，选填，radio、checkbox时必填，逗号分隔
    # regexp：正则，选填
    # required: 选填，默认为false
    configKeys:
    - key: jobStatusCallbackAddr
      title: 任务状态回调地址
      type: input
  user:
    # 参考平台配置
    configKeys:
    - key: jointCloudPermission
      title: 云际权限
      type: radio
      options: yes,no
administrator:
  username: "admin"
  password: "123456"
  email: ""
  phone: ""
module:
  storage:
    source:
      capacity: "100Gi"
      nfs:
        server: 192.168.203.72
        path: "/data/datasets/data"