dependencies:
  - name: mysql
    version: 8.5.9
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 14.3.2
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 7.1.3
    repository: https://charts.bitnami.com/bitnami
  - name: nginx-ingress-controller
    version: 7.6.9
    repository: https://charts.bitnami.com/bitnami
  - name: juicefs-csi-driver
    version: 0.6.1
    repository: https://juicedata.github.io/juicefs-csi-driver